# Generated by Django 5.1.5 on 2025-02-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SongSaver", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="name",
        ),
        migrations.AddField(
            model_name="artist",
            name="code",
            field=models.CharField(default="100", max_length=12),
        ),
        migrations.AddField(
            model_name="artist",
            name="desc",
            field=models.CharField(default="UNKNOWN", max_length=240),
        ),
        migrations.AddField(
            model_name="genre",
            name="code",
            field=models.CharField(default="100", max_length=12),
        ),
        migrations.AddField(
            model_name="genre",
            name="desc",
            field=models.CharField(default="UNKNOWN", max_length=240),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="playlist_name",
            field=models.CharField(max_length=240),
        ),
    ]
