# Generated by Django 5.0.2 on 2025-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongSaver', '0002_remove_artist_name_remove_genre_name_artist_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='curated_artists',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='genre',
        ),
        migrations.AddField(
            model_name='playlist',
            name='curated_artists',
            field=models.ManyToManyField(to='SongSaver.artist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.ManyToManyField(to='SongSaver.genre'),
        ),
    ]
