# Generated by Django 5.1.5 on 2025-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SongSaver", "0003_remove_playlist_curated_artists_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="curated_artists",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
