# Generated by Django 4.2.3 on 2023-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Anonymous', max_length=100)),
                ('title', models.TextField(default='Indie Boy', max_length=400)),
                ('link', models.URLField(default='Give it some thought', max_length=1000)),
            ],
        ),
    ]
